url: "https://javabean.ru"
title: "Michael Koltsov's den"
name: "Michael Koltsov's den"
description: "my cup of tea"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
google_analytics: 'UA-XXXXXXXX-X'
plugins:
  - jekyll-paginate

# Details for the RSS feed generator
author:         'Michael Koltsov'
